CREATE SCHEMA IF NOT EXISTS news;

DROP TABLE IF EXISTS news.items;

CREATE TABLE IF NOT EXISTS news.items (
	id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    pubTime BIGINT NOT NULL CHECK (pubTime > 0),
    link TEXT NOT NULL UNIQUE
);

-- SELECT * FROM items;