DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS items (
	id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    pubTime BIGINT NOT NULL CHECK (pubTime > 0),
    link TEXT NOT NULL UNIQUE
);

SELECT * FROM items;